# Generated by Django 4.2.1 on 2023-05-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_driver_driver_license_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_license_no',
            field=models.CharField(default='AS09', max_length=256),
        ),
    ]
