# Generated by Django 4.2.1 on 2023-05-31 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_driver_driver_license_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='is_a_driver',
            new_name='is_driver',
        ),
    ]
