# Generated by Django 4.2.1 on 2023-06-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_request_request_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_driver_id',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_user_id',
            field=models.CharField(max_length=5),
        ),
    ]
