# Generated by Django 4.2.1 on 2023-06-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_request_request_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_ride_id',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
