# Generated by Django 4.2.1 on 2023-06-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_review_review_ride_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_current_location',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
