# Generated by Django 4.2.1 on 2023-06-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_driver_driver_current_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_is_driving',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('ended', 'Ended'), ('completed', 'Completed'), ('active', 'Active')], max_length=20),
        ),
    ]
