# Generated by Django 4.2.1 on 2023-06-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_driver_driver_is_active_driver_driver_is_driving_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('ended', 'Ended'), ('completed', 'Completed')], max_length=20),
        ),
    ]
